'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''rdAjax class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class rdAjax

    '''<summary>
    '''headToFixThemesError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headToFixThemesError As System.Web.UI.HtmlControls.HtmlHead
End Class
