'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''_Default class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class _Default

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarget As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkbtnTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnTarget As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblPageSep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageSep1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkbtnSkills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnSkills As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblPageSep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageSep2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblPageSep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageSep3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkManual As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkMain As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkChangePwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkChangePwd As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Hr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hr1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAppraiseeSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppraiseeSession As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAppraiserLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppraiserLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optPersonal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optPersonal As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''optSubordinate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSubordinate As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''cboSubordinate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSubordinate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnLock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLock As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbltest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltest As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLock As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAppraisal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppraisal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDept As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDesignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesignation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblYOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYOS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDuties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDuties As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDuties_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDuties_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDuties_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDuties_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDuties_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDuties_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTarget1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarget1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAchievement1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAchievement1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTarget1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget1_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget1_5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget1_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget1_6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget1_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget1_7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget1_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget1_8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement1_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement1_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement1_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement1_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement1_5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement1_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement1_6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement1_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement1_7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement1_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement1_8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboWeighting_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboWeighting_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboPoints1_Appraisee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPoints1_Appraisee As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboDifficulty1_1stAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDifficulty1_1stAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboPoints1_1stAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPoints1_1stAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboDifficulty1_2ndAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDifficulty1_2ndAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboPoints1_2ndAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPoints1_2ndAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTarget2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarget2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAchievement2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAchievement2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTarget2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget2_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget2_5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget2_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget2_6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget2_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget2_7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget2_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget2_8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement2_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement2_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement2_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement2_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement2_5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement2_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement2_6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement2_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement2_7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement2_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement2_8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboWeighting_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboWeighting_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboPoints2_Appraisee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPoints2_Appraisee As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboDifficulty2_1stAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDifficulty2_1stAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboPoints2_1stAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPoints2_1stAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboDifficulty2_2ndAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDifficulty2_2ndAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboPoints2_2ndAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPoints2_2ndAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTarget3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarget3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAchievement3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAchievement3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTarget3_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget3_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget3_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget3_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget3_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget3_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget3_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget3_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget3_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget3_5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget3_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget3_6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget3_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget3_7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTarget3_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTarget3_8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement3_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement3_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement3_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement3_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement3_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement3_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement3_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement3_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement3_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement3_5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement3_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement3_6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement3_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement3_7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAchievement3_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAchievement3_8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboWeighting_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboWeighting_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboPoints3_Appraisee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPoints3_Appraisee As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboDifficulty3_1stAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDifficulty3_1stAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboPoints3_1stAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPoints3_1stAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboDifficulty3_2ndAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDifficulty3_2ndAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboPoints3_2ndAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPoints3_2ndAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Hr2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hr2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblComment_Target control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComment_Target As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComment_Achievement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComment_Achievement As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommentT_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentT_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentT_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentT_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentT_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentT_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentT_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentT_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentT_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentT_5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentT_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentT_6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentT_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentT_7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentT_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentT_8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentA_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentA_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentA_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentA_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentA_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentA_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentA_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentA_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentA_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentA_5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentA_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentA_6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentA_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentA_7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommentA_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentA_8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOverallComment_1st control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverallComment_1st As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOverallComment_1st_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverallComment_1st_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOverallComment_1st_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverallComment_1st_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOverallComment_1st_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverallComment_1st_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOverallComment_2nd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverallComment_2nd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOverallComment_2nd_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverallComment_2nd_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOverallComment_2nd_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverallComment_2nd_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOverallComment_2nd_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverallComment_2nd_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLevel As Global.System.Web.UI.WebControls.HiddenField
End Class
