'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''StaffSkills class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class StaffSkills

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarget As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkbtnTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnTarget As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblPageSep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageSep1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkbtnSkills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnSkills As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblPageSep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageSep2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblPageSep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageSep3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkManual As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkMain As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkChangePwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkChangePwd As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Hr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hr1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAppraiseeSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppraiseeSession As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAppraiserLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppraiserLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRating1_Desc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRating1_Desc1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRating1_Desc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRating1_Desc2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRating2_Desc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRating2_Desc1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRating2_Desc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRating2_Desc2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRating3_Desc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRating3_Desc1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRating3_Desc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRating3_Desc2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRating4_Desc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRating4_Desc1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRating4_Desc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRating4_Desc2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRating5_Desc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRating5_Desc1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRating5_Desc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRating5_Desc2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optPersonal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optPersonal As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''optSubordinate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSubordinate As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''cboSubordinate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSubordinate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSpace1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpace1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnLock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLock As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSpace2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpace2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLock As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAppraisal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppraisal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPoint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPoint As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory1_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisee_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisee_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbo1stAppraiser_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAppraiser_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCategory1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory1_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory1_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory1_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory1_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory2_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisee_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisee_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbo1stAppraiser_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAppraiser_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCategory2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory2_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory2_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory2_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory2_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory3_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory3_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisee_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisee_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbo1stAppraiser_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAppraiser_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCategory3_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory3_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory3_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory3_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory3_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory3_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory3_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory3_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory4_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory4_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisee_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisee_4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbo1stAppraiser_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAppraiser_4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCategory4_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory4_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory4_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory4_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory4_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory4_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory4_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory4_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory5_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory5_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisee_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisee_5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbo1stAppraiser_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAppraiser_5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCategory5_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory5_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory5_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory5_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory5_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory5_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory5_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory5_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory6_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory6_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisee_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisee_6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbo1stAppraiser_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAppraiser_6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCategory6_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory6_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory6_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory6_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory6_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory6_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory6_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory6_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory7_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory7_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisee_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisee_7 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbo1stAppraiser_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAppraiser_7 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCategory7_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory7_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory7_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory7_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory7_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory7_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory7_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory7_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory8_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory8_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisee_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisee_8 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbo1stAppraiser_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAppraiser_8 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCategory8_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory8_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory8_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory8_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory8_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory8_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory8_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory8_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory9_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory9_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisee_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisee_9 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbo1stAppraiser_9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAppraiser_9 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCategory9_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory9_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory9_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory9_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory9_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory9_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory9_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory9_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory10_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory10_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboAppraisee_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAppraisee_10 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbo1stAppraiser_10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAppraiser_10 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCategory10_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory10_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory10_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory10_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory10_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory10_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategory10_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory10_5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAppraisee_Total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppraisee_Total As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl1stAppraiser_Total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1stAppraiser_Total As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbo2ndAppraiser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo2ndAppraiser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLevel As Global.System.Web.UI.WebControls.HiddenField
End Class
