<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled 1</title>
<style type="text/css">
.style1 {
	margin-right: 54px;
}
</style>
</head>

<body>

<p>
<object classid="clsid:0002E55A-0000-0000-C000-000000000046" id="PivotTable1" class="style1">
	<param name="XMLData" value="&lt;xml xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot;&gt;
 &lt;x:PivotTable&gt;
  &lt;x:OWCVersion&gt;11.0.0.8166         &lt;/x:OWCVersion&gt;
  &lt;x:DisplayScreenTips/&gt;
  &lt;x:CubeProvider&gt;msolap.2&lt;/x:CubeProvider&gt;
  &lt;x:CacheDetails/&gt;
  &lt;x:ConnectionString&gt;Provider=MSDASQL.1;Persist Security Info=True;Extended Properties=&amp;quot;DSN=Munchy_HCRM;Description=Munchy_HCRM;UID=HRISMGR;APP=Microsoft Office 2007;WSID=WINSON-PC;DATABASE=Munchy_POC;Network=DBMSSOCN&amp;quot;;Initial Catalog=Munchy_POC&lt;/x:ConnectionString&gt;
  &lt;x:DataMember&gt;&amp;quot;Munchy_POC&amp;quot;.&amp;quot;dbo&amp;quot;.&amp;quot;Employee_AllInfo_Vw&amp;quot;&lt;/x:DataMember&gt;
  &lt;x:Name&gt;Employee Info&lt;/x:Name&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Company&lt;/x:Name&gt;
   &lt;x:Orientation&gt;Page&lt;/x:Orientation&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
   &lt;x:AllIncludeExclude&gt;Exclude&lt;/x:AllIncludeExclude&gt;
   &lt;x:IncludedValue&gt;PWP [TFP Demo Solutions Bhd]&lt;/x:IncludedValue&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Employee ID&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Employee Code Name&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Title&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;2&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Employee Code&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Employee Name&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;3&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;a_Middle Name&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Last Name&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;First Name2&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Middle Name2&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Last Name2&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Identity No&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;4&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Date Of Birth&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;5&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Place Of Birth&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Religion&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;6&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Marital Status&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;7&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Sex&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;8&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Citizenship&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;9&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Race&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;10&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Effective Date&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Join Date&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;11&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Confirm Date&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;12&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Resign Date&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;13&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Submit Date&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;14&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Resign Type&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Resign Flag&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;15&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Remark&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Basic Salary&lt;/x:Name&gt;
   &lt;x:DataType&gt;Number&lt;/x:DataType&gt;
   &lt;x:EncodedType&gt;adNumeric&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Basic Currency&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Pay To&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Pay type&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Pay Cycle&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Divsion&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;16&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Department&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;17&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Section&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Line&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Group&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Process&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Cost Center&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;18&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;TMS&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Job Grade&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;19&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Job Title&lt;/x:Name&gt;
   &lt;x:PLDataOrientation/&gt;
   &lt;x:PLPosition&gt;20&lt;/x:PLPosition&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Appraisal&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Employee Group&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Employment Type&lt;/x:Name&gt;
   &lt;x:EncodedType&gt;adVarWChar&lt;/x:EncodedType&gt;
   &lt;x:CompareOrderedMembersBy&gt;UniqueName&lt;/x:CompareOrderedMembersBy&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Data&lt;/x:Name&gt;
   &lt;x:Orientation&gt;Column&lt;/x:Orientation&gt;
   &lt;x:Position&gt;-1&lt;/x:Position&gt;
   &lt;x:DataField/&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PivotField&gt;
   &lt;x:Name&gt;Count of Employee Code&lt;/x:Name&gt;
   &lt;x:PLName&gt;Total2&lt;/x:PLName&gt;
   &lt;x:TotalNumber&gt;1&lt;/x:TotalNumber&gt;
   &lt;x:Orientation&gt;Data&lt;/x:Orientation&gt;
   &lt;x:Position&gt;1&lt;/x:Position&gt;
   &lt;x:ParentField&gt;Employee Code&lt;/x:ParentField&gt;
   &lt;x:Function&gt;Count&lt;/x:Function&gt;
  &lt;/x:PivotField&gt;
  &lt;x:PLTotal&gt;
   &lt;x:Name&gt;Total1&lt;/x:Name&gt;
   &lt;x:Caption&gt;Count of Join Date&lt;/x:Caption&gt;
   &lt;x:ParentField&gt;Join Date&lt;/x:ParentField&gt;
   &lt;x:TotalNumber&gt;0&lt;/x:TotalNumber&gt;
   &lt;x:Operator&gt;Count&lt;/x:Operator&gt;
  &lt;/x:PLTotal&gt;
  &lt;x:PivotData&gt;
   &lt;x:Top&gt;0&lt;/x:Top&gt;
   &lt;x:TopOffset&gt;0&lt;/x:TopOffset&gt;
   &lt;x:Left&gt;0&lt;/x:Left&gt;
   &lt;x:LeftOffset&gt;0&lt;/x:LeftOffset&gt;
   &lt;x:SeqNum&gt;12&lt;/x:SeqNum&gt;
   &lt;x:Expanded/&gt;
  &lt;/x:PivotData&gt;
  &lt;x:PivotView&gt;
   &lt;x:Label&gt;
    &lt;x:Caption&gt;Employee Info&lt;/x:Caption&gt;
   &lt;/x:Label&gt;
  &lt;/x:PivotView&gt;
 &lt;/x:PivotTable&gt;
&lt;/xml&gt;" />
</object>
</p>

</body>

</html>
